// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imumpwnkffzgerobcfbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltdW1wd25rZmZ6Z2Vyb2JjZmJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNjM3NzksImV4cCI6MjA3MzczOTc3OX0.D44uROSheZ4jXNnxkK0xtpSoI4IQG0LH-eus-8aViAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});